# Generated by Django 4.0.4 on 2023-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_name',
            new_name='category_code',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.IntegerField(unique=True),
        ),
    ]
