# Generated by Django 4.0.4 on 2023-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_code',
            field=models.IntegerField(default=2344, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.IntegerField(unique=True),
        ),
    ]
