# Generated by Django 4.1.4 on 2023-01-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_name',
        ),
        migrations.AddField(
            model_name='products',
            name='category_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
            preserve_default=False,
        ),
    ]
