# Generated by Django 4.0.4 on 2023-01-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
