# Generated by Django 4.0.4 on 2023-01-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='item_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_code',
            field=models.IntegerField(),
        ),
    ]
