# Generated by Django 4.1.4 on 2023-01-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_name_products_category_code_and_more'),
        ('orders', '0005_alter_orders_order_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='item_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rel', to='products.products'),
        ),
    ]
